/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* cells_not_processed =  1  *)
(* src = "c17.v:1" *)
module c17(G1, G2, G3, G4, G5, out1, out2);
  wire _0_;
  (* src = "c17.v:3" *)
  input G1;
  (* src = "c17.v:3" *)
  input G2;
  (* src = "c17.v:3" *)
  input G3;
  (* src = "c17.v:3" *)
  input G4;
  (* src = "c17.v:3" *)
  input G5;
  (* src = "c17.v:4" *)
  output out1;
  (* src = "c17.v:4" *)
  output out2;
  sky130_fd_sc_hd__nand2_1 _1_ (
    .A(G3),
    .B(G4),
    .Y(_0_)
  );
  sky130_fd_sc_hd__a22o_1 _2_ (
    .A1(G1),
    .A2(G3),
    .B1(G2),
    .B2(_0_),
    .X(out1)
  );
  sky130_fd_sc_hd__o21a_1 _3_ (
    .A1(G2),
    .A2(G5),
    .B1(_0_),
    .X(out2)
  );
endmodule
